### ISSUE TITLE
ocNews 1.9.4 did not update news

### ISSUE THREAD

**Issue by mschaaf** [Buschtrommel/ocNews#63]
With owncloud version 8.0 and news version 5.2.2 I get the following error in owncloud and the ocNews app says fetching folders failed.

Error on server is:
Exception: {"Message":"Could not determine user","Code":10,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_encryption\/lib\/helper.php(283): 

ocNews run on SailfishOS

**Comment by buschmann23** [comment]
It works for me with my ownCloud installation that is also on version 8.0 and 5.2.2. Maybe there is a problem with your ownCloud installation/configuration? Have you run the upgrade stuff after upgrading to the current versions? You could rerun it on by using the occ console client.

**Comment by mschaaf** [comment]
Yes I run it and it finished without errors.

**Comment by mschaaf** [comment]
Do you have file encryption enabled in your installation?

**Comment by buschmann23** [comment]
No. I don't have. I will install a test environment with actived encryption.

**Comment by buschmann23** [comment]
Ok. I now have set up an ownCloud test installation with file encryption enabled. But ocNews works for there too without any problems.
